### ISSUE TITLE
Run on my own dataset

### ISSUE THREAD

**Issue by xinedison** [zekunqian/BEVSee#3]
Dear author,
      Thanks for provide your work, it is a great work for me. My question is that how to run this algorithm on my own datasets. Any help to run on other datasets for train and test is ok. Thanks a lot.

**Comment by ChoLianJiet** [comment]
Hi, i would also wish to run on my own dataset, i want to try this with my office environment. Any ways to do it?

**Comment by zekunqian** [comment]
Thank you very much for your interest in our work! Let me organize the project details and I'll get back to you soon. Appreciate your patience! 😊

**Comment by ChoLianJiet** [comment]
Thank you so much @zekunqian ! We want to use this to actually try testing BEV on an open space area, but now, we want to test it with our office first, which is a small compound with a few people. I have already recorded 4 videos of the same setting, from different angle, but don't know how to infer them and produce a BEV plane over the time frame. Also getting raw data from them and plot a graph of number of people over time.

**Comment by zekunqian** [comment]
@ChoLianJiet  I think if your application scenario involves fixed cameras, you could first calibrate the camera poses, and then directly apply the SOTA methods from the Wildtrack dataset. Those methods that rely on camera calibration can be used directly.

**Comment by zekunqian** [comment]
@ChoLianJiet If you want to run BEVSee on your own multi-view videos or images, the existing `test_real.py` already works well - you just need to prepare your data in the right format and make a few simple modifications.

## Prerequisites

- BEVSee environment installed (see Installation in main README.md)
- Pre-trained models downloaded to `models/` directory
- 2 or more views of the same scene (videos or images ), with frame alignment

## Quick Start in 4 Steps

### Step 1: Extract Keypoints

Extract OpenPifPaf keypoints from each view's images.

**Command for each view:**

```bash
# Activate environment
conda activate bevsee

# Extract keypoints for view 1
python -m openpifpaf.predict \
    --checkpoint=shufflenetv2k30 \
    --json-output=/path/to/output/json/h1 \
    /path/to/view1/images/*.jpg

# Extract keypoints for view 2
python -m openpifpaf.predict \
    --checkpoint=shufflenetv2k30 \
    --json-output=/path/to/output/json/h2 \
    /path/to/view2/images/*.jpg
```

**Parameters:**
- `--checkpoint=shufflenetv2k30`: OpenPifPaf pre-trained model
- `--json-output`: Output directory for JSON files
- Last argument: Input image paths (wildcards supported)

### Step 2: Organize File Structure

Organize your data following BEVSee's standard format:

```
data/CSRD/real/Images/
└── YourScene_V2_G1/          # Your scene name
    ├── h1/                    # View 1 images
    │   ├── frame_0001.jpg
    │   ├── frame_0002.jpg
    │   └── ...
    ├── h2/                    # View 2 images
    │   ├── frame_0001.jpg
    │   ├── frame_0002.jpg
    │   └── ...
    ├── json/                  # OpenPifPaf keypoint JSONs
    │   ├── h1/
    │   │   ├── frame_0001.jpg.predictions.json
    │   │   ├── frame_0002.jpg.predictions.json
    │   │   └── ...
    │   └── h2/
    │       ├── frame_0001.jpg.predictions.json
    │       ├── frame_0002.jpg.predictions.json
    │       └── ...
    └── log/                   # Log directory (can be empty, will be created automatically)
```

**Reference:** Check `data/CSRD/real/Images/V2_G1/` structure as an example.

**Important notes:**
- Image filenames should correspond across views (same filename for same timestamp)
- JSON file naming format: `{image_name}.predictions.json`
- For 3 views, create h1, h2, h3 directories

### Step 3: Modify test_real.py

Edit `test_real.py` file with three simple changes:

**Change 1:** Update config name (line 13)

```python
# Original:
cfg = Config('CSRDR_V2_G1_tracking')

# Change to your scene:
cfg = Config('CSRDR_YourScene_V2_G1_tracking')
```

**Change 2:** Add to dataset list (lines 80-82)

```python
cfg.real_dataset_name_list = ['CSRDR_V2_G1_tracking', 'CSRDR_V2_G3_tracking', 'CSRDR_V3_G2_tracking',
                              'CSRDR_V3_G3_tracking', 'CSRDR_V3_G5_tracking', 'CSRDR_V4_G1_tracking',
                              'CSRDR_V4_G2_tracking',
                              'CSRDR_YourScene_V2_G1_tracking']  # Add your scene
```

**Change 3:** Add configuration to config.json

Edit `config/config.json` and add your scene configuration:

```json
{
  "CSRDR_YourScene_V2_G1_tracking": {
    "scene_path": "./data/CSRD/real/Images/YourScene_V2_G1",
    "view_num": 2,
    "view_label": ["h1", "h2"],
    "dataset_type": "real",
    "is_tracking": true
  }
}
```

**Parameters:**
- `scene_path`: Your scene data directory
- `view_num`: Number of views (2 for 2 views, 3 for 3 views)
- `view_label`: List of view directory names, e.g., ["h1", "h2", "h3"]
- `dataset_type`: Keep as "real"
- `is_tracking`: Keep as true

### Step 4: Run Inference

```bash
python test_real.py
```

**Output:**
- Results will be saved in `YourScene_V2_G1/log/` directory
- Contains detected person positions and orientations for each frame

## Visualization

To generate visualization images (similar to those in the paper), add to `test_real.py`:

```python
# Add these configurations in test_real.py (around line 37)
cfg.draw_fig = True
cfg.test_draw_fig_num = 20  # Visualize 20 frames
cfg.is_colorful = True
```

Visualization results will be saved in the log directory.

**Comment by ChoLianJiet** [comment]
Thank you for the guide, by the way, under the train_net.py there is this variable img_size_dict in line 423
```
    img_size_dict = {}
    img_size_dict['V2_G1'] = [2688, 1512]
    img_size_dict['V2_G3'] = [2688, 1512]
    img_size_dict['V3_G2'] = [2688, 1512]
    img_size_dict['V3_G3'] = [2704, 1520]
    img_size_dict['V3_G5'] = [2704, 1520]
    img_size_dict['V4_G1'] = [2704, 1520]
    img_size_dict['V4_G2'] = [2704, 1520]
```

I'm replacing YourScene with OF, so it is CSRDR_OF_V2_G1_tracking.

I need to add:
```
img_size_dict['OF_V2'] = [2704, 1520]
```
Is it correct?

Because i am getting this error after i run python test_real.py
```
Load reidnet all parameter from:  models/csrdr.pth
Load reidnet all parameter from:  models/csrdr_reid.pth
Reload reid from models/csrdr_reid.pth
  0%|                                                                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Python Projects\bevsee_demo\test_real.py", line 85, in <module>
    test_more_view_aggregation_cosine_similarity(cfg)
  File "C:\Python Projects\bevsee_demo\train_net.py", line 478, in test_more_view_aggregation_cosine_similarity
    img_size = img_size_dict[sub_seq_name]
KeyError: 'OF_V2'
```

**Comment by zekunqian** [comment]
@ChoLianJiet This is used to estimate camera intrinsic parameters. You need to provide it based on the actual image dimensions and add it to this img_size_dict.

**Comment by ChoLianJiet** [comment]
@zekunqian I see, i have 4 views, so does it mean that all 4 of them must be of the same image dimensions?

**Comment by zekunqian** [comment]
@ChoLianJiet Yes, ideally we need accurate camera intrinsic parameters for each camera. Without calibrated intrinsics, we have to estimate them from the image dimensions.

**Comment by ChoLianJiet** [comment]
@zekunqian Thank you! I also encountered this under train_net.py
```
start training
Load loconet all parameter from:  models/csrdr.pth
Load reidnet all parameter from:  models/csrdr.pth
Load reidnet all parameter from:  models/csrdr_reid.pth
Reload reid from models/csrdr_reid.pth
Test log\mono21+11+bevsee+test_csrdrat2025-11-18_17-42-19\CSRDR_OF_V2_G1_tracking: 100%|█████████████████████████████████████████████| 655/655 [04:11<00:00,  2.60it/s]
Processing CSRDR_OF_V2_G1_tracking:   0%|                                                                                                        | 0/1 [04:11<?, ?it/s] 
Traceback (most recent call last):
  File "C:\Python Projects\bevsee_demo\test_real.py", line 85, in <module>
    test_more_view_aggregation_cosine_similarity(cfg)
  File "C:\Python Projects\bevsee_demo\train_net.py", line 485, in test_more_view_aggregation_cosine_similarity
    test_info = test(candidate_view_dataset, model_mono, model_reid, device, 0, cfg, time_extra)
  File "C:\Python Projects\bevsee_demo\train_net.py", line 2063, in _test_monoreid_cam_gt_centroid_soft_choose_more_view_without_annotation_with_pred_tracking_original_way
    'view_avg': agg_avg,
UnboundLocalError: local variable 'agg_avg' referenced before assignment

```

it seems like the agg_avg, pair_avg, view1_avg, view2_avg, comp_view_num is not defined, i'm assuming this condition
```
if len(total_cos_list) > 0 and len(view1_cos_list) > 0 and len(pair_cos_list) > 0:
```
is not met?



Another thing is that my config.json looks like this, for CSRDR_OF_V2_G1_tracking:
```
    "CSRDR_OF_V2_G1_tracking": {
      "root_view": "data/CSRD/real/Images/OF_V2_G1/h1",
      "comp_view_list": [
        "data/CSRD/real/Images/OF_V2_G1/h2",
        "data/CSRD/real/Images/OF_V2_G1/h3",
        "data/CSRD/real/Images/OF_V2_G1/h4"
      ],
      "label": "None",
      "output": "data/CSRD/real/Images/OF_V2_G1/log",
      "json": "data/CSRD/real/Images/OF_V2_G1/json",
      "annotation": "data/CSRD/real/GT_txt",
      "view": 4,
      "struct": {
        "images": "",
        "labels": "",
        "features": ""
      },
    }
```
which i copied from the other ones, and not
```
  "CSRDR_OF_V2_G1_tracking": {
    "scene_path": "./data/CSRD/real/Images/OF_V2_G1",
    "view_num": 2,
    "view_label": ["h1", "h2"],
    "dataset_type": "real",
    "is_tracking": true
  }
```

**Comment by zekunqian** [comment]
@ChoLianJiet It looks like openpifpaf didn't detect enough targets. Check what the detection results look like, and try lowering the openpifpaf threshold a bit, something like this. Since I haven't tested this project in a long time, I don't quite remember the specific details. Take a look at how to properly adjust the specific parameters for running openpifpaf, something like this:

```bash
python -m openpifpaf.predict \
    --checkpoint=shufflenetv2k30 \
    --instance-threshold=0.2 \
    --seed-threshold=0.15 \
    --json-output=/path/to/output/json/h1 \
    /path/to/view1/images/*.jpg
```

**Comment by ChoLianJiet** [comment]
Hmmm...

I have added these 
```
 if 'agg_avg' not in locals():
            print("[Warning] agg_avg was never computed — probably no valid views found.")
            agg_avg = 0.0
        if 'pair_avg' not in locals():
            print("[Warning] pair_avg was never computed — probably no valid views found.")
            pair_avg = 0.0
        if 'view1_avg' not in locals():
            print("[Warning] view1_avg was never computed — probably no valid views found.")
            view1_avg = 0.0
        if 'view2_avg' not in locals():
            print("[Warning] view2_avg was never computed — probably no valid views found.")
            view2_avg = 0.0
        if 'comp_view_num' not in locals():
            print("[Warning] comp_view_num was never computed — probably no valid views found.")
            comp_view_num = 0
```
in  train_net.py, it is still not computed. I got:
```
Load reidnet all parameter from:  models/csrdr.pth
Load reidnet all parameter from:  models/csrdr_reid.pth
Reload reid from models/csrdr_reid.pth
Test log\mono21+11+bevsee+test_csrdrat2025-11-18_18-08-53\CSRDR_OF_V2_G1_tracking: 100%|█████████████████████████████████████████████| 655/655 [05:14<00:00,  2.09it/s]
[Warning] agg_avg was never computed — probably no valid views found._G1_tracking: 100%|█████████████████████████████████████████████| 655/655 [05:14<00:00,  3.49it/s] 
[Warning] pair_avg was never computed — probably no valid views found.
[Warning] view1_avg was never computed — probably no valid views found.
[Warning] view2_avg was never computed — probably no valid views found.
Processing CSRDR_OF_V2_G1_tracking: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [05:14<00:00, 314.05s/it] 
 View 4: 0.0

```

Hence, the folder log\mono21+11+bevsee+test_csrdrat2025-11-18_18-08-53\CSRDR_OF_V2_G1_tracking is empty
